if(NOT DEFINED SKALAXC_DOXYGEN_SOURCE_DIR)
  message(FATAL_ERROR "SKALAXC_DOXYGEN_SOURCE_DIR is required")
endif()

if(NOT DEFINED SKALAXC_DOXYGEN_BINARY_DIR)
  message(FATAL_ERROR "SKALAXC_DOXYGEN_BINARY_DIR is required")
endif()

if(NOT DEFINED SKALAXC_DOXYGEN_PROJECT_VERSION)
  set(SKALAXC_DOXYGEN_PROJECT_VERSION "development")
endif()

file(MAKE_DIRECTORY "${SKALAXC_DOXYGEN_BINARY_DIR}")
set(SKALAXC_DOXYGEN_OUTPUT_DIRECTORY
    "${SKALAXC_DOXYGEN_BINARY_DIR}/doxygen")
configure_file(
  "${SKALAXC_DOXYGEN_SOURCE_DIR}/Doxyfile.in"
  "${SKALAXC_DOXYGEN_BINARY_DIR}/Doxyfile"
  @ONLY
)