# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b831c3dc5d27d9da294ae4e915773b99aa24a7c5  # frozen: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff
        args: [--config, pyproject.toml, --fix]
      # Run the formatter.
      - id: ruff-format
        args: [--config, pyproject.toml]
