# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b831c3dc5d27d9da294ae4e915773b99aa24a7c5  # frozen: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff
        args: [--config, pyproject.toml, --fix]
      # Run the formatter.
      - id: ruff-format
        args: [--config, pyproject.toml]

  - repo: https://github.com/srstevenson/nb-clean
    rev: f745b986570ef12cfbe0cfe20a7e0271c328914f  # frozen: 4.0.1
    hooks:
      - id: nb-clean

  - repo: local
    hooks:
      - id: mypy-skala
        name: mypy (Skala runtime)
        entry: mypy
        language: system
        args:
          - --config-file
          - pyproject.toml
          - --num-workers
          - "4"
          - skala
        pass_filenames: false
        always_run: true

      - id: mypy-model
        name: mypy (model)
        entry: mypy
        language: system
        args:
          - --config-file
          - pyproject.toml
          - --num-workers
          - "4"
          - model
        pass_filenames: false
        always_run: true

      - id: mypy-gauxc
        name: mypy (GauXC)
        entry: mypy
        language: system
        args:
          - --config-file
          - pyproject.toml
          - --num-workers
          - "4"
          - gauxc
        pass_filenames: false
        always_run: true

      - id: mypy-docs
        name: mypy (documentation)
        entry: mypy
        language: system
        args:
          - --config-file
          - pyproject.toml
          - --num-workers
          - "4"
          - docs
        pass_filenames: false
        always_run: true
