name: skala-cpu
channels:
  - conda-forge
dependencies:
  - ase
  - dftd3-python
  - e3nn
  - h5py
  - hdf5 >=2.1,<2.2
  - jinja2
  - markdown-it-py
  - numpy <2.5
  - opt_einsum_fx
  - pandas
  - pyarrow
  - pyscf >=2.8,<2.14
  - pyyaml
  - python
  - pytorch * cpu_*
  - scipy
# Testing and development
  - memray
  - pre-commit
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-randomly
  - pytest-timeout
  - ruff
  - mypy >=2
  - pip:
    - huggingface_hub
    - pandas-stubs
    - pyarrow-stubs >=20,<21
    - scipy-stubs
    - types-PyYAML
