name: skala-cpu
channels:
  - conda-forge
dependencies:
  - ase
  - dftd3-python
  - e3nn
  - h5py
  - hdf5 >=2.1,<2.2
  - numpy <2.5
  - opt_einsum_fx
  - pyscf >=2.8,<2.14
  - python
  - pytorch * cpu_*
# Testing and development
  - memray
  - pre-commit
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-randomly
  - pytest-timeout
  - ruff
  - mypy >=2
  - pip:
    - huggingface_hub
