name: skala-gpu
channels:
  - conda-forge
dependencies:
  - ase
  - azure-core
  - azure-identity
  - dftd3-python
  - e3nn
  - h5py
  - hdf5 >=1.14,<2
  - numpy
  - opt_einsum_fx
  - pyscf >=2.8,<2.14
  - python
  - pytorch-gpu
  - qcelemental
  - cuda-version >=12,<13
  - cuda-nvcc >=12,<13
  - cutensor >=2
  # Testing and development dependencies
  - pre-commit
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-randomly
  - pytest-timeout
  - ruff
  - mypy >=2
  - pip:
    - huggingface_hub
    - gpu4pyscf-cuda12x >=1.8,<1.9
