name: skala-cpp-integration
channels:
- conda-forge
dependencies:
- cmake
- cxx-compiler
- ninja
- nlohmann_json
- libtorch * cpu_*
- pytorch >=2.9 cpu_*  # Only required to produce example features.
- skala
