name: "GauXC tests"

on:
  push:
    branches: [main]
    paths: &gauxc-test-paths
      - '.github/workflows/gauxc-test.yml'
      - 'gauxc/**'
      - 'pixi.lock'
      - 'pixi.toml'
      - 'pyproject.toml'
  pull_request:
    branches: [main]
    paths: *gauxc-test-paths
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 4
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Print CPU diagnostics
      uses: ./.github/actions/cpu-diagnostics

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
      with:
        pixi-version: v0.75.0
        environments: default
        activate-environment: true
        locked: true
        cache: false

    - name: Run GauXC unit tests
      run: pytest -v gauxc/tests/