name: "GauXC tests"

on:
  push:
    branches: [main]
    paths: &gauxc-test-paths
      - '.github/workflows/gauxc-test.yml'
      - '.github/actions/setup-pixi/**'
      - 'gauxc/**'
      - 'pixi.lock'
      - 'pixi.toml'
      - 'pyproject.toml'
  pull_request:
    branches: [main]
    paths: *gauxc-test-paths
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 4
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Print CPU diagnostics
      uses: ./.github/actions/cpu-diagnostics

    - name: Setup Pixi
      uses: ./.github/actions/setup-pixi
      with:
        environment: default

    - name: Run GauXC unit tests
      run: pytest -v gauxc/tests/